// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type UserBase struct {
	UserID         int32
	UserAccount    string
	UserPassword   string
	UserSait       string
	UserLoginTime  sql.NullTime
	UserLogoutTime sql.NullTime
	UserLoginIp    sql.NullString
	UserCreatedAt  sql.NullTime
	UserUpdatedAt  sql.NullTime
}

type UserInfo struct {
	UserID       int32
	UserAccount  string
	UserName     sql.NullString
	UserAvatar   sql.NullString
	UserState    int16
	UserPhone    sql.NullString
	UserGender   sql.NullInt16
	UserBirthday sql.NullTime
	UserEmail    sql.NullString
	UserIsAuth   int16
	CreateAt     sql.NullTime
	UpdatedAt    sql.NullTime
}

type UserToken struct {
	UserID       int32
	RefreshToken string
	ExpiresAt    time.Time
}

type UserVerify struct {
	VerifyID       int32
	VerifyOtp      string
	VerifyKey      string
	VerifyKeyHash  string
	VerifyType     sql.NullInt32
	IsVerified     sql.NullInt32
	IsDeleted      sql.NullInt32
	VerifyCreated  sql.NullTime
	VerifyUpdated  sql.NullTime
	FailedAttempts int32
	LockUntil      sql.NullTime
}
