@url_dev = http://localhost:8080/v1

###
GET {{url_dev}}/ping
Content-Type: application/json

POST {{url_dev}}/user/register
Content-Type: application/json

{
  "account": "test@test.com",
  "password": "123456"
}

// register with email
POST {{url_dev}}/user/register-email
Content-Type: application/json

{
  "email": "test@test.com"
}

// verify OTP
POST {{url_dev}}/user/verify-otp
Content-Type: application/json

{
  "email": "test@test.com",
  "otp": "344598"
}

// complete register
POST {{url_dev}}/user/complete-registration
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456",
  "name": "test"
}

// login
POST {{url_dev}}/user/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}