version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=quanglong
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-network
  crm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      # - .:/app # This is for dockerfile.dev.v1
      - ./:/app # This is for dockerfile.dev.v2
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - crm-network
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
