// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/tqlong1609/go_backend_ecommerce/internal/controllers"
	"github.com/tqlong1609/go_backend_ecommerce/internal/repo"
	"github.com/tqlong1609/go_backend_ecommerce/internal/services"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controllers.UserController, error) {
	iUserRepository := repo.InitUserRepository()
	iUserService := services.InitUserService(iUserRepository)
	userController := controllers.InitUserController(iUserService)
	return userController, nil
}
