// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	CategoryID int32  `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
	Name       string `gorm:"column:name;not null" json:"name"`
	ParentID   int32  `gorm:"column:parent_id" json:"parent_id"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
