server: 
  port: 8080
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: test
  maxIdleConnection: 10
  maxOpenConnection: 100
  maxLifeTime: 3600
logger:
  log_level: debug
  file_path: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28 
  compress: true