server: 
  port: 8080
  mode: dev
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: test
  maxIdleConnection: 10
  maxOpenConnection: 100
  maxLifeTime: 3600
postgresql:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: quanglong
  database: store_db
  maxIdleConnection: 10
  maxOpenConnection: 100
  maxLifeTime: 3600
logger:
  log_level: debug
  file_path: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28 
  compress: true
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0